[package]
name = "atomic-waker"
# When publishing a new version:
# - Update CHANGELOG.md
# - Create "v1.x.y" git tag
version = "1.1.1"
authors = [
  "Stjepan Glavina <stjepang@gmail.com>",
  "Contributors to futures-rs",
]
edition = "2018"
rust-version = "1.36"
description = "A synchronization primitive for task wakeup"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/smol-rs/atomic-waker"
keywords = ["waker", "notify", "wake", "futures", "async"]
categories = ["asynchronous", "concurrency"]
exclude = ["/.*"]

[dependencies]
# Uses portable-atomic polyfill atomics on targets without them
portable-atomic = { version = "1", optional = true, default-features = false }

[dev-dependencies]
futures = "0.3.5"
